/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-spring-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source sky walking info")
            }
        }
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("redis.clients:jedis")
    implementation("org.apache.skywalking:apm-toolkit-trace:8.8.0")
    implementation("org.apache.skywalking:apm-toolkit-meter:8.8.0")
}