/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.1.1/userguide/multi_project_builds.html
 */

rootProject.name = "source"

//include("app")
//include("init")
//include("cmd")
//include("tool")
//include("basic")
//include("lettuce")
//include("mapper")
//include("resilience4j")
//include("sentinel")
//include("graphQlBasic")

//include("empty")
include("spring")
//include("spring-web")
//include("actuator")
//include("datasource")
//include("web-flux")
//include("sw")
