/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "source"

//include("app")
//include("init")
//include("cmd")
//include("tool")
//include("net")
//include("lettuce")
//include("mapper")
//include("resilience4j")
//include("sentinel")
//include("graphQlBasic")
//include("engine")
include("leetcode")

//include("empty")
//include("spring") // done
//include("spring-web")
//include("actuator")
//include("datasource")
//include("web-flux")
//include("sw")
//include("transaction")
