/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "source"

//include("app")  // no
//include("init") // no
//include("cmd")  // no
//include("tool") // done
include("net")
//include("lettuce") // done
include("mapper")
//include("resilience4j") // done
include("sentinel")
include("graphQlBasic")
//include("engine")  // done
//include("leetcode") // done
include("dub-api")

//include("empty")  // no
//include("spring") // done
include("spring-web") // done
//include("actuator") // done
//include("datasource") // done
include("web-flux")
include("sw")
//include("transaction") // done
//include("redisson") // done
//include("mybatis") // done
include("protobuf")
include("dub-provider", "dub-consumer")
