logging:
  level:
    root: INFO


dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    logger: slf4j
    qos-port: 33333
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181