logging:
  level:
    root: INFO


dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    logger: slf4j
    qos-port: 33333
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
