/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-common-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source lettuce info")
            }
        }
    }
}

dependencies {
//    implementation("io.lettuce:lettuce-core:5.3.0.RELEASE")
//    implementation("redis.clients:jedis:3.6.3")
    implementation("redis.clients:jedis:2.9.0")
}