/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("org.yqj.source.java-spring-conventions")
}

dependencies {
    // javax cache
//    implementation("javax.cache:cache-api:1.1.1")

    // spring cache support
//    implementation("org.springframework.boot:spring-boot-starter-cache")
//    implementation("org.springframework.boot:spring-boot-starter-data-redis")
//    implementation("com.fasterxml.jackson.core:jackson-core")
//    implementation("com.fasterxml.jackson.core:jackson-databind")

    // web demo
    implementation("org.springframework.boot:spring-boot-starter-web")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source spring info")
            }
        }
    }
}

