
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-spring-conventions")
    id("com.google.protobuf") version "0.9.4"
}

dependencies {
    implementation("com.google.protobuf:protobuf-java:4.26.1")
    implementation("com.google.protobuf:protobuf-java-util:4.26.1")

    implementation("io.grpc:grpc-stub:1.63.0")
    implementation("io.grpc:grpc-protobuf-lite:1.63.0")
    implementation("javax.annotation:javax.annotation-api:1.3.2")
}


sourceSets {
    main {
        java {
            srcDir("src/main/proto")
        }
    }
}

protobuf{
    protoc {
        artifact = "com.google.protobuf:protoc:4.26.1"
    }
    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.63.0"
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                create("grpc") {
                    option("lite")
                }
            }
        }
    }
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source spring info")
            }
        }
    }
}