/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-application-conventions")
}

application {
    mainClass.set("org.yqj.source.app.App")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source app info")
            }
        }
    }
}