logging:
  level:
    root: INFO

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    logger: slf4j
  protocol:
    name: tri
    port: 50052
    serialization: fastjson2
  provider:
    serialization: fastjson2
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos

