logging:
  level:
    root: INFO

dubbo:
  application:
    name: dubbo-springboot-demo-provider
    logger: slf4j
  protocol:
    name: tri
    port: 50052
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
