/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
//    compileOnly("org.projectlombok:lombok:1.8.20")
//    annotationProcessor("org.projectlombok:lombok:1.8.20")

    // guava
    implementation("com.google.guava:guava:30.1-jre")
//    implementation("org.projectlombok:lombok:1.18.20")

    // logback dependency


    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
}