/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-common-conventions")
}

tasks.register("hello") {
    group = "person"
    description = "this is hello description"
    doLast {
        println("hello world task finish !!")
    }
}