/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-common-conventions")
}

dependencies {
//    compileOnly("javax.cache:cache-api:1.1.1")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source cmd info")
            }
        }
    }
}
