/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-common-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source resilience4j info")
            }
        }
    }
}

dependencies {
    implementation("io.github.resilience4j:resilience4j-all:1.6.1")
}