import org.jetbrains.kotlin.fir.declarations.builder.buildImport

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
}

dependencies {
    // spring plugin version
    implementation("org.springframework.boot:spring-boot-gradle-plugin:2.6.2")

}