import org.jetbrains.kotlin.fir.declarations.builder.buildImport

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
}
