import org.jetbrains.kotlin.fir.declarations.builder.buildImport

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
}

kotlin{
    jvmToolchain(21)
}

dependencies {
    // spring plugin version
    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.4.2")

    // kotlin plugin version
    implementation(libs.kotlinGradlePlugin)
}