/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-common-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source init info")
            }
        }
    }
}

dependencies {

    annotationProcessor("org.mapstruct:mapstruct:1.4.2.Final")

    implementation("org.mapstruct:mapstruct:1.4.2.Final")
}