/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.yqj.source.java-common-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source graphQl basic info")
            }
        }
    }
}

dependencies {
    // https://mvnrepository.com/artifact/com.graphql-java/graphql-java
    implementation("com.graphql-java:graphql-java:17.1")

    // https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    implementation("org.apache.commons:commons-lang3:3.12.0")
}